module.exports = {
    // 1. 하드웨어
    STATUS_CHANGE: 'STATUS_CHANGE',
    DEVICE_ERROR: 'DEVICE_ERROR',
    BREAKER_ALARM: 'BREAKER_ALARM',
    LOOP_SENSE: 'LOOP_SENSE',

    // 2. 프로세스
    INBOUND_SUCCESS: 'INBOUND_SUCCESS',
    OUTBOUND_SUCCESS: 'OUTBOUND_SUCCESS',
    GHOST_VEHICLE: 'GHOST_VEHICLE',

    // 3. 운영자 조작
    OPERATOR_ACTION: 'OPERATOR_ACTION', // 기타
    MANUAL_OPEN: 'MANUAL_OPEN',
    MANUAL_CLOSE: 'MANUAL_CLOSE',
    MANUAL_INBOUND: 'MANUAL_INBOUND',
    MANUAL_EXIT: 'MANUAL_EXIT', // 단순 개방 출차
    MANUAL_PAYMENT: 'MANUAL_PAYMENT', // 현장 수납
    
    UPDATE_PLATE: 'UPDATE_PLATE',
    UPDATE_TIME: 'UPDATE_TIME',
    UPDATE_TYPE: 'UPDATE_TYPE',
    
    REFUND: 'REFUND',
    RESET_DISCOUNT: 'RESET_DISCOUNT',
    
    EMERGENCY_OPEN: 'EMERGENCY_OPEN',

    // 4. 결제
    PAYMENT_REQ: 'PAYMENT_REQ',
    PAYMENT_CANCEL: 'PAYMENT_CANCEL',
    SCAN_DISCOUNT: 'SCAN_DISCOUNT'
};